//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedServiceItem
    {
        public int Id { get; set; }
        public string Remark { get; set; }
        public AppliedServiceItemResolution Resolution { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ServiceItem ServiceItem { get; set; }
    }
}
