//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceForms.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarServiceFormsDBContext : DbContext
    {
        public CarServiceFormsDBContext()
            : base("name=CarServiceFormsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<WorkOrder> WorkOrder { get; set; }
        public virtual DbSet<WordOrderInformation> WordOrderInformation { get; set; }
        public virtual DbSet<WorkOrderInstruction> WorkOrderInstruction { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceItemGroup> ServiceItemGroup { get; set; }
        public virtual DbSet<ServiceItem> ServiceItem { get; set; }
        public virtual DbSet<AppliedServiceItem> AppliedServiceItem { get; set; }
        public virtual DbSet<ServiceItemServiceType> ServiceItemServiceType { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItem { get; set; }
        public virtual DbSet<InvoiceItemDescription> InvoiceItemDescription { get; set; }
    }
}
