//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceForms.Model
{
    using System;
    
    public enum ServiceType : int
    {
        Interval = 0,
        Inspection = 1,
        OilChange = 2
    }
}
