//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceForms.Model
{
    using System;
    
    public enum ServiceItemGroupType : int
    {
        Electricity = 0,
        Tires = 1,
        Underside = 2,
        EngineBay = 3,
        FinishingWork = 4,
        Exterior = 5
    }
}
