//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceItem()
        {
            this.AppliedServiceItem = new HashSet<AppliedServiceItem>();
            this.ServiceTypes = new HashSet<ServiceItemServiceType>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public bool HasRemarks { get; set; }
        public int Order { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ServiceItemGroup ServiceItemGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedServiceItem> AppliedServiceItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceItemServiceType> ServiceTypes { get; set; }
    }
}
